### ISSUE TITLE
bin-packing support for multiple bins

### ISSUE THREAD

**Issue by radumg** [DynamoDS/RefineryToolkits#114]
We should support packing items across multiple bins

As requested by **Patryk Wozniczka** during the Toronto hackathon, I coded a quick overloader for `Pack2D` that accepts multiple bins and when the first bin is full, the next bin is used etc.

**Comment by radumg** [comment]
Original request was for 2D packing support, but no reason we shouldn't look at 3D as well since the underlying library seems to support it.

- [ ] 2D packing in multiple bins

- [ ] 3D packing in multiple bins

**Comment by radumg** [comment]
2D is now done, it works like this
- pack as many items as possible in first bin
- move to next bin & pack whatever is left
- repeat till all bins have been packed
- introduced new `PackResult` class for strongly-typed representation of results, output is still a dictionary for Dynamo compatibility

**Comment by radumg** [comment]
To implement this, the code is undergoing some pretty big refactors.

**Comment by Vanman989** [comment]
Hi, I don't want to be rude and don't know really where to post requests if that is appropriate at all! These nodes are awesome. Would be great if it had an output of bin locations and packing without rotating. The algorithms from the below post would be amazing as packing options too. Would be able to achieve so much with that. 

https://github.com/juj/RectangleBinPack/blob/master/RectangleBinPack.pdf

**Comment by Vanman989** [comment]
Hi, I don't want to be rude and don't know really where to post requests if that is appropriate at all! These nodes are awesome. Would be great if it had an output of bin locations and packing without rotating. The algorithms from the below post would be amazing as packing options too. Would be able to achieve so much with that.

https://github.com/juj/RectangleBinPack/blob/master/RectangleBinPack.pdf

**Comment by radumg** [comment]
Hi @Vanman989 , yes,  please feel free to [open a new issue](https://github.com/DynamoDS/RefineryToolkits/issues/new) when you have an idea for a feature request, letting us know how and why the use-case would be valuable.

As for the above :

- [x]  the nodes already exposes bin location : the bins are packed in their supplied location and are not modified, so whatever location the has when you pass it as input, it'll come out the same

- [x] the bin-packing algorithms uses `best short fit`, `best long fit`, `best area fit`, which you can find around page 19 of the PDF you linked - unless i'm mistaken, @SHKnudsen would be able to confirm exactly which algorithms were used.

**Comment by radumg** [comment]
3D done too

![image](https://user-images.githubusercontent.com/11439624/63017909-6aa04580-be8f-11e9-8c35-0b4733caff20.png)
