### ISSUE TITLE
No rotation function

### ISSUE THREAD

**Issue by Vanman989** [DynamoDS/RefineryToolkits#120]
Hi, my requests all base around the architecture program Revit. Being able to use your nodes to pack Views(bins) on Sheets. Being able to choose no rotation of 2D bins would be one thing to allow for this. Will submit the other requests as separate issues if you guys would be keen to adding them as development. I know a lot of people struggle to attain a good bin packing method for packing views on sheets.

**Comment by radumg** [comment]
Similar with issue #121 , we'll close this for now but keep it in the backlog for future improvements.
