### ISSUE TITLE
Packing.PackCuboids return wither not touching or overlapping solids

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/RefineryToolkits#129]
The cuboids are sometimes with gaps along the Z Axis or overlapping.

![image](https://user-images.githubusercontent.com/14221455/64622027-f5b92080-d3e6-11e9-8c09-6d53d26ed1fa.png)

![image](https://user-images.githubusercontent.com/14221455/64621669-5c8a0a00-d3e6-11e9-8e00-e2fbb1531152.png)

**Comment by SHKnudsen** [comment]
Hi @paoloemilioserra 

Can you provide us with the graph or a sample of it so we can investigate this?

**Comment by paoloemilioserra** [comment]
@SHKnudsen  sure thing, here it is.
[PackingIssue.zip](https://github.com/DynamoDS/RefineryToolkits/files/3597018/PackingIssue.zip)
