### ISSUE TITLE
Shortest Path Sample File Error

### ISSUE THREAD

**Issue by mkeshavarzi** [DynamoDS/RefineryToolkits#130]
`PathFinding.ShortestPath` component requires `visGraph` and Points to be provided as input, but is instead using other types

![image](https://user-images.githubusercontent.com/23546447/65716055-3d7cb080-e053-11e9-8d68-445414030bed.png)

**Comment by radumg** [comment]
Thanks @mkeshavarzi , good catch ! We've recently changed that node to not require a `visGraph` as input, will update the samples shortly and close this issue when we resolve it.

**Comment by SHKnudsen** [comment]
@radumg looks like you fixed the sample file in #128 

i'll close this for now
