### ISSUE TITLE
Download Sample

### ISSUE THREAD

**Issue by Vanman989** [DynamoDS/RefineryToolkits#139]
Hi, sorry I'm struggling to download a sample of to use the 2D bin packing nodes properly. An image or 1.3 script

**Comment by radumg** [comment]
Hi @Vanman989 , we might need a bit more info : are you having a hard time downloading the samples or getting them to run ?

Here's a direct download link for the bin-packing sample : [bin packing sample](https://raw.githubusercontent.com/DynamoDS/RefineryToolkits/master/samples/SpacePlanning/dt_GenerativeToolkit_PackingRectangles_BAF.dyn)

Also, please note this package requires Dynamo version 2.1 or newer, as noted in the [requirements](https://github.com/DynamoDS/RefineryToolkits#prerequisites) section.

**Comment by Vanman989** [comment]
The sample PNG didn't have enough resolution and I'm just to new to figure out where the download button for the scripts were. There was one for the PNG but not the scripts. Turns out alt click! thanks for the help :)

**Comment by radumg** [comment]
Glad to help!
