### ISSUE TITLE
Packing.PackCuboids Fails when too many Containers for Items.

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/RefineryToolkits#142]
Found this bug while messing around with Bin Packing.

Demonstrated here:
https://user-images.githubusercontent.com/15744724/103705289-07252500-4f68-11eb-847e-9284e8f51bde.mp4

and proposed fix here:
https://github.com/johnpierson/RefineryToolkits/commit/453cef766a850703992f8363b130c117acd85944

**Comment by radumg** [comment]
Super nice detective work @johnpierson 🙌!
